### PR TITLE
Adding `cf_units`.

### PR DESCRIPTION
**Pull request by ocefpaf**
First release of `cf_units`.

### CODE REVIEW

**Comment by pelson** [comment]
:+1: once travis is happy.

**Comment by ocefpaf** [comment]
@pelson we are used to call `udunits2` and not `udunits` version 2.  I will rename it for conda-recipes-scitools.  (I guess that comes from a time when scientist needed both udunits installed so things would work.)

**Comment by pelson** [comment]
hmmm. Strange error on OSX. I'm not sure what to make of that - its not quite one I've seen before...:

```
The following NEW packages will be INSTALLED:

cf_units: v0.0.1-np18py27_0 file:///Users/travis/miniconda/conda-bld/osx-64/

curl: 7.30.0-2 defaults

hdf5: 1.8.9-2 defaults

libnetcdf: 4.2.1.1-2 defaults

netcdf4: 1.1.1-np18py27_0 defaults

numpy: 1.8.2-py27_0 defaults

openssl: 1.0.1k-1 defaults

pip: 6.0.8-py27_0 defaults

python: 2.7.9-1 defaults

readline: 6.2-2 defaults

setuptools: 14.0-py27_0 defaults

sqlite: 3.8.4.1-0 defaults

tk: 8.5.18-0 defaults

udunits: 2.2.17-4 http://conda.binstar.org/SciTools/osx-64/

zlib: 1.2.8-0 defaults

===== testing package: cf_units-v0.0.1-np18py27_0 =====

import: u'units'

Traceback (most recent call last):

File "/Users/travis/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>

import units

File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/units/__init__.py", line 20, in <module>

from .unit import *

File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/units/unit.py", line 199, in <module>

_cv_convert_float = _lib_ud.cv_convert_float

File "/Users/travis/miniconda/envs/_test/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__

func = self.__getitem__(name)

File "/Users/travis/miniconda/envs/_test/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__

func = self._FuncPtr((name_or_ordinal, self))

AttributeError: dlsym(RTLD_DEFAULT, cv_convert_float): symbol not found

TESTS FAILED: cf_units-v0.0.1-np18py27_0

```

**Comment by rhattersley** [comment]
> AttributeError: dlsym(RTLD_DEFAULT, cv_convert_float): symbol not found

Looks very similar to the [problems we had with Iris](https://github.com/SciTools/iris/issues/295) - i.e. The UDUNITS dynamic library cannot be found. Given that previously we've needed to [explitictly point to the shared library](https://github.com/SciTools/conda-recipes-scitools/blob/569d4677d4cf5f92e7556cb0dd94e9ed8bcbdda7/iris/build.sh#L14), I'm surprised it's working on the *other* platforms!

**Comment by ocefpaf** [comment]
Thanks @rhattersley I will take a look and try to this PR.

**Comment by ocefpaf** [comment]
@pelson and @rhattersley I will wait until I sort all the renaming and docstrings out and fix https://github.com/SciTools/cf_units/issues/14 before fixing this PR.

**Comment by ocefpaf** [comment]
@pelson PR https://github.com/SciTools/cf_units/pull/21 solved the packaging issue.  However, I would not merge this yet.  I am pointing to master instead of a release.

Should we make a release?  Or wait until I sort https://github.com/SciTools/cf_units/pull/22 out?

**Comment by rhattersley** [comment]
> Should we make a release? Or wait until I sort SciTools/cf_units#22 out?

If it would help to have a release then make one. You can always make another release soon after.

**Comment by ocefpaf** [comment]
OK!  Release early, release often.  Rebased and pointing to v0.1.0.

**Pull request merged**
