### PR TITLE
Update mo_pack to 0.2.0

### PR DESCRIPTION
**Pull request by rhattersley**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rhattersley I only see the `v0.1.0` tag on GitHub. (https://github.com/SciTools/mo_pack/releases)

**Comment by rhattersley** [comment]
Yeah, sorry - I'm getting ahead of myself. I should have mentioned that this PR is not ready to merge yet. :unamused: I'm waiting for SciTools/mo_pack#7 to be merged and then I'll tag the new release.

**Comment by ocefpaf** [comment]
The error `No module named binstar_client.utils` is due to an annoying updating/renaming of modules (See https://github.com/pelson/Obvious-CI/pull/13).

A workaround is to `conda install --yes` ~~`conda-server`~~ `anaconda-client` in the CIs (hopefully continuum did not renamed it again this week!).

**Comment by rhattersley** [comment]
> I only see the v0.1.0 tag on GitHub.

@ocefpaf - mo_pack 0.2.0 is released now

**Comment by ocefpaf** [comment]
Thanks for letting me know!  [I just updated ours](https://github.com/ioos/conda-recipes/pull/366).

 As soon as things get a little quitter here at my day job I will start adding all the packages in the  IOOS channel to `conda-forge` to avoid this effort duplication.

**Pull request merged**
