### PR TITLE
make check

### PR DESCRIPTION
**Pull request by ocefpaf**
Just checking...

I am not bumping the build number because we don't really need new builds for these two. (Maybe we don't need the `make check` at all.)

### CODE REVIEW

**Comment by QuLogic** [comment]
But if you don't bump, nothing gets built?

**Comment by ocefpaf** [comment]
> But if you don't bump, nothing gets built?

Indeed. I just added that as "place holders"  for future updates.

**Comment by ocefpaf** [comment]
I went ahead and bumped the build numbers.

**Comment by ocefpaf** [comment]
All hell broke loose with conda's latest updates for Windows that has nothing to do with this PR :unamused: 

But Travis-CI (OSX) is not happy with `make check` for geos.  @QuLogic any ideas?

**Comment by pelson** [comment]
> All hell broke loose with conda's latest updates for Windows that has nothing to do with this PR

Indeed. I wonder if they know their post-link.sh script is doing this for conda-env?

**Comment by pelson** [comment]
(I commented https://github.com/conda/conda/issues/1753#issuecomment-154988598)

**Comment by ocefpaf** [comment]
AppVeyor is behaving again :tada: 

@QuLogic I am thinking about skipping this `make check` on OSX for geos. Unless you know have some idea how to fix it.

**Comment by QuLogic** [comment]
I found [an upstream ticket](https://trac.osgeo.org/geos/ticket/299) with some idea, but no apparent resolution in the end. If you have a Mac, maybe you can try out whatever was suggested there?

**Comment by ocefpaf** [comment]
> If you have a Mac, maybe you can try out whatever was suggested there?

No Mac... Sorry.

**Comment by ocefpaf** [comment]
> I found [an upstream ticket](https://trac.osgeo.org/geos/ticket/299) with some idea, but no apparent resolution in the end.

That is 4 years old and, as you said, no resolution.  I am bypassing the tests for now.  They were never a blocker to the packages that depend on proj.4.  I just added them for completeness.

**Pull request merged**
