### PR TITLE
Patch Grib to work with Python 3.

### PR DESCRIPTION
**Pull request by QuLogic**
Generally very large due to the extraneous SWIG stuff. It does manage to fix several hundred tests on Python 3. I'm not totally sure it doesn't break anything on Python 2 though, so this might change a little bit.

### CODE REVIEW

**Comment by pelson** [comment]
Thanks @QuLogic. Has this been fed back to the ECMWF? I'm sure they would be interested in py3 compatibility...

**Comment by QuLogic** [comment]
No, and it seems I've broken Python 2 a little bit. Trying to get `FILE` working is quite a pain; it would be better if they had a `grib_open` kind of thing and never relied on Python's `file`. I wonder how pygrib does it, since they support 2 and 3...

**Comment by QuLogic** [comment]
Python 2 should be working again, but I'm not totally sure this messing around with `FILE`s on Python 3 is good enough since I get deadlocks when running iris tests (but since half of the tests don't work with Py3, that may not be the root cause.)

**Comment by QuLogic** [comment]
After doing some reading, I see that `fclose` will call `close` on the underlying fd. That's a problem since the fd is in use in Python's `file`. If `fclose` isn't called, then the `FILE` structures will leak. It's starting to look like supporting `file` and `io.IOBase` is unlikely, and Grib should move to a `grib_open` function for the Python wrapper side.

**Comment by QuLogic** [comment]
OK, using `dup`, the `fclose` no longer closes files twice and there are no longer any dead locks as far as I can tell.

**Comment by pelson** [comment]
Ok, I'm going to merge this without a major review of the patch. If there are any failures in the Iris build relating to GRIB, this change would explain it.

Incidentally, I spoke to @marqh about this, and it appears that the GRIB API is being renamed and re-worked a little, so we should engage with that process regarding these changes.

:+1:

**Comment by QuLogic** [comment]
FYI, there are several SWIG-generated files in there, so it appears quite a bit larger than you'd expect. The main changes are in the first few files. I did test with Iris, so there shouldn't be any new failures on Python 2.

**Pull request merged**
