### PR TITLE
Updated shapely to latest release

### PR DESCRIPTION
**Pull request by ocefpaf**
Conda updated its default Shapely to 1.5.8, which is compiled against geos-3.3.3.  The update caused cartopy to crash on MacOS (for people using the IOOS channel).  This update might also be the reason behind the issue https://github.com/SciTools/cartopy/issues/612.

### CODE REVIEW

**Comment by pelson** [comment]
Which GEOS are you targetting with this change? Does both Continuum and scitools GEOS both work with this change?

**Comment by ocefpaf** [comment]
> Which GEOS are you targetting with this change?

Same as before geos >=3.4 from scitools.

> Does both Continuum and scitools GEOS both work with this change?

Nope.  I was unable to make the default shapely, that comes with geos-3.3.3, to work with cartopy.  See https://travis-ci.org/ioos/conda-recipes/builds/60733895#L5291.

I do not own a Mac to make further tests.  For example: I do not know if scitools shapely can work with the default geos-3.3.3 and cartopy.  All I know is that the default shapely and default geos won't.  Since the default geos is not available for [Windows](https://binstar.org/anaconda/geos/files) I think that test is not worth the effort.

**Comment by pelson** [comment]
Aha, thanks @ocefpaf - I've just re-read the **critical** line:

```
Conda updated its default Shapely to 1.5.8
```

At one point, we pinned shapely down to a [specific version](https://github.com/SciTools/conda-recipes-scitools/commit/77a82d0c67318f68d923e7cc59e58593c4e1d5b9#diff-0b1cd7d54a9d18290078ac34fcbaa936L27) to prevent this happening, but in the end I kind of went for the approach of assuming Continuum would update their own build of GEOS at the same time as shapely.

@asmeurer - are you aware that the shapely you are shipping is compiled against an old GEOS, and that it doesn't seem that shapely deals well with picking up a newer GEOS than was compiled against (using conda at least)? Do you guys have any plans for updating your GEOS build? Incidentally, if you need the history of building GEOS & shapely on Windows, #29 may be of interest (plus of course, https://github.com/SciTools/conda-recipes-scitools/blob/master/geos/bld.bat).

**Comment by asmeurer** [comment]
Ping @ilanschnell @groutr

**Pull request merged**
