### PR TITLE
Build matrix using ObviousCI.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by pelson** [comment]
Seems to be a problem with the build conditions on windows...:

```
Executing: obvci_conda_build_dir.py . scitools --channel main  --build-condition "numpy >=1.8" "python >2.7,<3"
Fetching package metadata: ...... 
Resolving distributions from 14 recipes... 
Computed that there are 53 distributions from the 14 recipes:
Resolved dependencies, will be built in the following order: 
	expat-2.1.0-6 (will be built: False)
	geos-3.4.2-3 (will be built: False)
	proj4-4.9.1-0 (will be built: False)
	pyepsg-0.2.0-py34_0 (will be built: True)
	pyepsg-0.2.0-py26_0 (will be built: True)
	pyepsg-0.2.0-py33_0 (will be built: True)
	pyepsg-0.2.0-py27_0 (will be built: False)
	pyke-1.1.1-py34_0 (will be built: True)
	pyke-1.1.1-py26_0 (will be built: True)
	pyke-1.1.1-py33_0 (will be built: True)
```

I'll give it a spin on my Windows machine to see if I can figure out the problem.

**Comment by QuLogic** [comment]
Looks like you need OWSLib for Python 3.4...

**Comment by pelson** [comment]
> Looks like you need OWSLib for Python 3.4...

Yeah. Need to update to >= v0.9 of owslib. There is a bug in here which needs addressing in ObviousCI so that it doesn't try to build cartopy for py3 if the dependencies aren't there.

**Comment by pelson** [comment]
Ok, I'm going to go ahead and merge this, and deal with any fallout subsequently.

**Pull request merged**
