### PR TITLE
Use obvious-ci from conda-forge.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by ocefpaf** [comment]
You beat me to it.  I was about to push that :smile: 

But you forgot: `obvci_conda_build_dir.py` &rarr; `obvci_conda_build_dir`

**Comment by pelson** [comment]
> You beat me to it. I was about to push that :smile:

Apologies. If you have something ready to go, please do push and I'll merge that. :+1:

**Comment by ocefpaf** [comment]
> Apologies. If you have something ready to go, please do push and I'll merge that.

You first sir :wink: 

(I already delete my branch!)

**Comment by pelson** [comment]
Done. Thanks @ocefpaf

**Comment by ocefpaf** [comment]
Thank you.

**Pull request merged**
