### PR TITLE
Update to v3.1

### PR DESCRIPTION
**Pull request by bjlittle**
Update to the latest point release of `imagehash`

### CODE REVIEW

**Comment by bjlittle** [comment]
@pelson Please merge https://github.com/pelson/Obvious-CI/pull/67 to unblock the PR and all that follow, thanks!

**Comment by lbdreyer** [comment]
Interesting error..

It does look similar to the errors we were getting with conda-forge feedstocks. We had to rerender those feedstocks, which removed the download of `https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py`

**Comment by bjlittle** [comment]
@lbdreyer Yeah, similar problem, but obvious-ci is the forerunner to conda-forge ... but https://github.com/pelson/Obvious-CI/pull/67 should fix this problem.

**Comment by bjlittle** [comment]
@lbdreyer Thanks to @ocefpaf in https://github.com/SciTools/conda-recipes-scitools/pull/211, this PR is unblocked ... happy days!

**Pull request merged**
