### PR TITLE
Recipe for iris-sample-data.

### PR DESCRIPTION
**Pull request by bjlittle**
@marqh

### CODE REVIEW

**Comment by bjlittle** [comment]
@marqh I tidied the Anaconda Cloud `dev` channel for `cube_browser` to purge all platform packages older than `0.2.1.dev0` ... it was getting rather noisy.

This PR should hopefully push up:
* cube_browser `0.2.2.dev0`
* iris `1.10.dev1`
* iris_sample_data `1.0.0.dev0`

**Comment by bjlittle** [comment]
@marqh Now targeting `cube_browser` tag `v1.0` :beers:

**Comment by bjlittle** [comment]
@marqh Finally ...

**Comment by marqh** [comment]
:beers: indeed

cheers :)

**Comment by bjlittle** [comment]
@marqh Awesome!

**Pull request merged**
