### PR TITLE
pin conda-build to 2.0.6

### PR DESCRIPTION
**Pull request by marqh**
pin conda-build to 2.0.6

API changes have broken aspects of conda-build-all

### CODE REVIEW

**Comment by marqh** [comment]
ping @lbdreyer

**Comment by ocefpaf** [comment]
There are some advantages of bumping to latest conda-build. I remember having some issue with `2.0.6`.

I also believe that https://github.com/SciTools/conda-build-all/pull/71 fixes the issue for good.

**Comment by marqh** [comment]
> There are some advantages of bumping to latest conda-build. I remember having some issue with 2.0.6.
> 
> I also believe that SciTools/conda-build-all#71 fixes the issue for good.

SciTools/conda-build-all#71 is not currenlty fully functional

given our current broken state, I'd prefer to merge this, establish it works and get some of our stuck builds uploaded.

once SciTools/conda-build-all#71 or similar is ready, this is an easy thing to revert

**Comment by ocefpaf** [comment]
> SciTools/conda-build-all#71 is not currenlty fully functional

Why? The CIs errors are not related to the PR. But I am keen to fix anything that I may be missing.

> given our current broken state,

Don't stop on my account :smile: 

I used 2.0.6 in the IOOS channel but now I do need `2.0.9` at least to fix some bugs in the packages I am shipping.

**Comment by lbdreyer** [comment]
Note: This has been pinned to conda-build 2.0.10 as that was the last time the build that occurs after a PR is merged passed and was able to upload to the channel. 
([See the build after PR #214 was merged](https://travis-ci.org/SciTools/conda-recipes-scitools/builds/177932610#L516))

**Pull request merged**
