### PR TITLE
Updated shapely - recent changes have made it easier to build.

### PR DESCRIPTION
**Pull request by pelson**
Note: Eventually, thanks to this fix going into upstream shapely, we will be able to remove shapely from this repository and make use of conda's default version.

### CODE REVIEW

**Comment by pelson** [comment]
Ping @sgillies / @asmeurer / @cgohlke - this is what I've done to build the latest (master) shapely on Windows. @sgillies, looks like recent work on libgeos.py have made things much easier. :+1:

**Comment by sgillies** [comment]
Yay. :tada:

**Comment by asmeurer** [comment]
@ilanschnell

**Comment by ilanschnell** [comment]
Thanks, shapely is already up-to-date in the official Anaconda repository.

**Comment by ocefpaf** [comment]
@ilanschnell do you have Windows binaries for Shapely?

**Comment by ilanschnell** [comment]
Nope, only Unix so far.  But once time allows we'll look into it.

**Pull request merged**
