### PR TITLE
Removed the test outputs for cartopy and iris.

### PR DESCRIPTION
**Pull request by pelson**
iris: from ~27MB to ~2MB
cartopy: ~8MB to ~ 1.5MB

### CODE REVIEW

**Comment by ocefpaf** [comment]
Big :+1:

**Comment by ocefpaf** [comment]
You did not bump iris build number.

**Comment by pelson** [comment]
> You did not bump iris build number.

You did it for me with the next PR :wink:

**Comment by ocefpaf** [comment]
I lost track of what got merged first.

**Pull request merged**
