### PR TITLE
Update the recipes for Mule + Utils vn1.4

### PR DESCRIPTION
**Pull request by stevewardle**
Just updating the recipes now that a new version is out...

(If you're wondering where vn1.3 went... I was originally planning to add that, but some issues came up which forced us to release vn1.4 earlier than planned; so as far as SciTools etc. are concerned there's not much point having the intermediate version)

### CODE REVIEW

**Comment by stevewardle** [comment]
@marqh @bjlittle Could someone pick this up for me please?

**Comment by marqh** [comment]
Hi Steve

apologies for the tedium, but

you will need to navigate to

https://circleci.com/gh/<insertYourUserID>/conda-recipes-scitools/tree/master

and click on 'follow project' to enable CircleCI in your fork. Then submit another commit here and the test should re-start.

That is the new and "improved" CircleCi behavior :/

you should only need to do this once.......
  (for each user and each repository)

/me sighs

**Comment by stevewardle** [comment]
No worries... I get a 404 for the link above though...  do I need to sign up there or something?  Log-in with my Github credentials?

**Comment by marqh** [comment]
> No worries... I get a 404 for the link above though... do I need to sign up there or something? Log-in with my Github credentials?

sorry, it hid the `<insertYourUserID>` in markup

**Comment by marqh** [comment]
hi @stevewardle 

the build is running fine on Linux.  On M4cOS and M$Windows it is skipping these builds.  I suspect this is due to dependency resolution; it could be linked to mopack

are you content to progress with linux success and follow up on other operating systems at a later date?
(for the record, I am)

**Comment by stevewardle** [comment]
Yes I'm fine with that, thanks

**Pull request merged**
