### PR TITLE
Bump up nc_time_axis to 1.0.1

### PR DESCRIPTION
**Pull request by lbdreyer**
:crossed_fingers: :crossed_fingers: :crossed_fingers: :crossed_fingers: 

and for extra luck :four_leaf_clover:

### CODE REVIEW

**Comment by lbdreyer** [comment]
appveyor is still causing problems
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-build-all
  - python 3.6*
```

I had hoped that conda would have changed something over the weekend and, like magic, it would all be fixed... wishful thinking, of course!

**Comment by marqh** [comment]
@lbdreyer i have had issues with python 3.6 on other platforms, perhaps it's worth sticking with 3.5 for now?

**Comment by dkillick** [comment]
@marqh unfortunately it is not that simple.

**Comment by ocefpaf** [comment]
I think I know how to fix this... Let me try... Hold on.

**Comment by dkillick** [comment]
@ocefpaf brilliant :100:

**Comment by pelson** [comment]
Closed due to the deprecation of this repo. #250

**Pull request closed without merging**
