### PR TITLE
Pyke for python 3

### PR DESCRIPTION
**Pull request by ocefpaf**
Not sure if there is a better way to do this.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I am missing something here... I cannot see why two extra build appear in the AppVeyor matrix.  This setup is virtually identical to ours. (See https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.845.)

**Comment by rhattersley** [comment]
> I cannot see why two extra build appear in the AppVeyor matrix

You've added two extra entries to the [environment matrix](https://github.com/ocefpaf/conda-recipes-scitools/blob/pykepy3k/appveyor.yml#L14).

**Comment by ocefpaf** [comment]
> You've added two extra entries to the environment matrix.

I did.  But that should crate py2 and py3 for x86 and x64.

In our [config](https://github.com/ioos/conda-recipes/blob/master/appveyor.yml#L17) that works just fine.

**Comment by pelson** [comment]
> I did. But that should crate py2 and py3 for x86 and x64.

You've done that in this PR and in another PR - it is hard to see with unified diff, but I believe once merged, this will produce 6 matrix items.

Essentially, I don't think you need to make any changes to appveyor.yaml (except fix the typos)...

**Comment by ocefpaf** [comment]
I restored the original `appveyor.yml`.

In out repo I had to change ` CONDA_PY: "3"` to ` CONDA_PY: "34"` and [`- cmd: set CONDA_PY=%CONDA_PY%`](https://github.com/ocefpaf/conda-recipes/blob/master/appveyor.yml#L38) before building.  Otherwise AppVeyor would fail.

**Comment by pelson** [comment]
It is definitely finding the wrong VS for py3 (it is choosing VS 2008 vn9 rather than vn10). Maybe the CONDA_PY does need setting. https://github.com/pelson/Obvious-CI/blob/master/scripts/obvci_appveyor_python_build_env.cmd#L35 doesn't appear to care though...

**Comment by ocefpaf** [comment]
> It is definitely finding the wrong VS for py3 (it is choosing VS 2008 vn9 rather than vn10). Maybe the CONDA_PY does need setting.

OK.  I implemented that here and clean-up my mess of submitting the matrix twice.

(Sorry for the mess :flushed: I am going crazy this week teaching Bash/Git/Python the whole afternoon and trying to get some work done in the morning.)

**Comment by pelson** [comment]
Super job. Thanks @ocefpaf & good luck with the software carpentry - I imagine you're an excellent teacher.

**Comment by QuLogic** [comment]
I'm not seeing build 1 of pyke on the scitools channel, only build 0 which doesn't seem to be built with the correct source files?

**Comment by pelson** [comment]
> I'm not seeing build 1 of pyke on the scitools channel, only build 0 which doesn't seem to be built with the correct source files?

For linux? Does #105 look like it may be targeting this?

**Comment by QuLogic** [comment]
Yes, it looks like the build might have bumped it now.

**Pull request merged**
