### PR TITLE
esmf

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @pp-mo

### CODE REVIEW

**Comment by ocefpaf** [comment]
I guess will have to limit numpy to 1.10 here.

**Comment by pelson** [comment]
> I guess will have to limit numpy to 1.10 here.

Hmmm. There was also a thing about using ObviousCI vs conda-build-all which needed to get implemented (can't remember exactly what now, but I believe we may need to transfer to conda-build-all).

**Comment by ocefpaf** [comment]
> can't remember exactly what now, but I believe we may need to transfer to conda-build-all

:+1:

**Comment by pp-mo** [comment]
Hi @ocefpaf 
Sorry to be so long getting back to this.
I just tested this in an envionment with iris and iris conda-requirements.txt
Unfortunately this is not working for me.
On attempting to import ESMF, I am now getting :
  > OSError: /home/h05/itpp/miniconda/envs/p27_iris_esmpyXsci/lib/./libnetcdff.so.6: undefined symbol: nc_rename_grp

That seems weird, like it just has the wrong netcdf build, or a broken one.
Any idea what that can mean ?

I have the following selected lines from  "conda list" (if it helps at all) :
```
esmf                      7.0.0                         0    scitools
esmpy                     7.0.0                    py27_0    scitools
hdf5                      1.8.9                         1    defaults
imagesize                 0.7.0                    py27_0    defaults
iris                      1.9.2                np18py27_0    scitools
netcdf-fortran            4.4.3                         0    scitools
netcdf4                   1.1.1                np18py27_0    defaults
```

**Comment by ocefpaf** [comment]
I will take a look at that tomorrow. Not sure what is going on...

**Comment by pp-mo** [comment]
Thanks @ocefpaf !
Thanks for your help, and sorry to rely on you so much for this.
I was previously attempting to build the recipe myself, but I again failed to make it work within the limitations of our standard installed software stack, and it rapidly got beyond my understanding!

> I just tested this in an envionment with iris and iris conda-requirements.txt

I should perhaps explain what I actually *ran* :
```$ conda create -n p27_iris_esmpy python=2.7 iris esmpy --file ~/git/iris/conda-requirements.txt```

It didn't work first time though : 
I had to retry, after cleaning out some earlier package downloads from conda-forge + ioos that didn't work (like "rm -rf ~/miniconda/pkgs/netcdf-fortran*" and I think some others).
So, I'm hoping I have now resolved those problems completely + correctly.
I can post the whole resulting package list, if that would help...

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf ! Thanks for your help, and sorry to rely on you so much for this.

My pleasure. I am just glad that someone is looking into integrating ESMF into iris :smile: 

> I was previously attempting to build the recipe myself, but I again failed to make it work within the limitations of our standard installed software stack, and it rapidly got beyond my understanding!

>> I just tested this in an envionment with iris and iris conda-requirements.txt

> I should perhaps explain what I actually *ran* :
```$ conda create -n p27_iris_esmpy python=2.7 iris esmpy --file ~/git/iris/conda-requirements.txt```

> It didn't work first time though : 
I had to retry, after cleaning out some earlier package downloads from conda-forge + ioos that didn't work (like "rm -rf ~/miniconda/pkgs/netcdf-fortran*" and I think some others).
Without that, it wasn't downloading the newer builds.

Here is another way to do it:

```shell
conda clean --yes --tarballs --lock --index-cache --packages --source-cache
```

> So, I'm hoping I have now resolved those problems completely + correctly.
I can post the whole resulting package list, if that would help...

So it is working now? Good! Let me know if I can help you any further.

**Comment by pp-mo** [comment]
> So it is working now? 

No, sorry I gave the wrong impression!
I was just posting some extra details, the problem remains.
To summarise what I'm doing, it is something like...
```
$ conda create -n p27_iris_esmpy python=2.7 iris esmpy --file ~/git/iris/conda-requirements.txt
$ source activate p27_iris_esmpy
$ python -c "import ESMF"
 . . . --> . . .
OSError: /home/h05/itpp/miniconda/envs/p27_iris_esmpyXsci/lib/./libnetcdff.so.6: undefined symbol: nc_rename_grp
```

I will try your suggestion of "conda clean" though, as forcing it to reload everything might be a safer basis for investigation.

**Comment by ocefpaf** [comment]
> No, sorry I gave the wrong impression!

No problem. Here is what I test to ensure the scitools version is in working conditions. I removed all channels but the `defaults` and then I issues the following commands:

```shell
> conda create -n TEST -c scitools esmpy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /home/filipe/miniconda/envs/TEST:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    netcdf-fortran-4.4.3       |                0         769 KB  scitools
    esmf-7.0.0                 |                0        15.3 MB  scitools
    esmpy-7.0.0                |           py27_0         134 KB  scitools
    ------------------------------------------------------------
                                           Total:        16.2 MB

The following NEW packages will be INSTALLED:

    curl:           7.45.0-0      defaults
    esmf:           7.0.0-0       scitools
    esmpy:          7.0.0-py27_0  scitools
    hdf5:           1.8.15.1-2    defaults
    krb5:           1.13.2-0      defaults
    libgcc:         4.8.5-1       defaults
    libnetcdf:      4.3.3.1-3     defaults
    mkl:            11.3.1-0      defaults
    netcdf-fortran: 4.4.3-0       scitools
    numpy:          1.11.0-py27_0 defaults
    openssl:        1.0.2g-0      defaults
    pip:            8.1.1-py27_1  defaults
    python:         2.7.11-0      defaults
    readline:       6.2-2         defaults
    setuptools:     20.7.0-py27_0 defaults
    sqlite:         3.9.2-0       defaults
    tk:             8.5.18-0      defaults
    wheel:          0.29.0-py27_0 defaults
    zlib:           1.2.8-0       defaults
```

As you can see it is correctly downloading `esmf`, `esmpy`, and `netcdf-fortran` from the `scitools` channel while the rest is from `defaults`. Then I activated the `TEST` env and check the `linkages`:

```shell
> source activate TEST
discarding /home/filipe/miniconda/bin from PATH
prepending /home/filipe/miniconda/envs/TEST/bin to PATH
(TEST)
[filipe@system76 0  ~/Dropbox/pymodules/02-conda-forge]  
> conda inspect linkages esmf       
esmf
----

curl-7.45.0-0:
    libcurl.so.4 (lib/libcurl.so.4)

esmf-7.0.0-0:
    libesmf.so (lib/libesmf.so)

hdf5-1.8.15.1-2:
    libhdf5.so.10 (lib/libhdf5.so.10)
    libhdf5_hl.so.10 (lib/libhdf5_hl.so.10)

libgcc-4.8.5-1:
    libgcc_s.so.1 (lib/libgcc_s.so.1)
    libgfortran.so.3 (lib/libgfortran.so.3)
    libgomp.so.1 (lib/libgomp.so.1)
    libquadmath.so.0 (lib/libquadmath.so.0)
    libstdc++.so.6 (lib/libstdc++.so.6)

libnetcdf-4.3.3.1-3:
    libnetcdf.so.7 (lib/libnetcdf.so.7)

netcdf-fortran-4.4.3-0:
    libnetcdff.so.6 (lib/libnetcdff.so.6)

openssl-1.0.2g-0:
    libcrypto.so.1.0.0 (lib/libcrypto.so.1.0.0)
    libssl.so.1.0.0 (lib/libssl.so.1.0.0)

zlib-1.2.8-0:
    libz.so.1 (lib/libz.so.1)

system:
    libc.so.6 (/lib64/libc.so.6)
    libdl.so.2 (/lib64/libdl.so.2)
    libm.so.6 (/lib64/libm.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    librt.so.1 (/lib64/librt.so.1)

not found:

```

As you can see there is nothing *not found* and the only system libs used are expected. Now for the test:

```
python -c "import ESMF; print(ESMF.__version__)"
7.0.0
```

Can you repeat those steps so we can try to figure out what is different in your system?

**Comment by pp-mo** [comment]
> Can you repeat those steps so we can try to figure out what is different in your system?

I have done that to check, and there is no problem as it stands.

But that much already worked fine.

To get Iris working I must add "--file ~/git/iris/conda-requirements.txt".
It's when I do that, it fails as previously described.

**Comment by ocefpaf** [comment]
This file https://github.com/SciTools/iris/blob/master/conda-requirements.txt, right?

I will take a look to see who is downgrading/upgrading what to cause the missing symbols. Hold on...

**Comment by pp-mo** [comment]
> This file https://github.com/SciTools/iris/blob/master/conda-requirements.txt, right?

Correct.
Thanks !

**Comment by pp-mo** [comment]
P.S. the "linkages" output, if it helps ...
```
(TEST)[itpp@eld238 iris_main]$ conda inspect linkages esmf
esmf
----

esmf-7.0.0-0:
    libesmf.so (lib/libesmf.so)

hdf5-1.8.9-1:
    libhdf5.so.7 (lib/libhdf5.so.7)
    libhdf5_hl.so.7 (lib/libhdf5_hl.so.7)

libgcc-4.8.5-1:
    libgcc_s.so.1 (lib/libgcc_s.so.1)
    libgfortran.so.3 (lib/libgfortran.so.3)
    libgomp.so.1 (lib/libgomp.so.1)
    libquadmath.so.0 (lib/libquadmath.so.0)
    libstdc++.so.6 (lib/libstdc++.so.6)

libnetcdf-4.2.1.1-0:
    libnetcdf.so.7 (lib/libnetcdf.so.7)

netcdf-fortran-4.4.3-0:
    libnetcdff.so.6 (lib/libnetcdff.so.6)

zlib-1.2.8-0:
    libz.so.1 (lib/libz.so.1)

system:
    libc.so.6 (/lib64/libc.so.6)
    libdl.so.2 (/lib64/libdl.so.2)
    libm.so.6 (/lib64/libm.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    librt.so.1 (/lib64/librt.so.1)
    linux-vdso.so.1 ()

not found:

(TEST)[itpp@eld238 iris_main]$
```

**Comment by ajdawson** [comment]
There are different versions of netcdf in your version @pp-mo (compared to the output pasted by @ocefpaf). As @ocefpaf says, there is probably a change to a library version induced by the conda requirements of iris. It might be simple to sort by specifying all dependencies in one go, at least conda will tell you if there is something that cannot be resolved.

**Comment by pp-mo** [comment]
> There are different versions of netcdf in your version

Thanks @ajdawson 

Just to recap, back in the original PR on conda-forge the problem was *not* to get Iris and ESMPy to work together, which did work almost immediately.
The problem was that the Iris **tests** are currently rather heavily reliant on netcdf4=1.1.1 , given some nasty subsequent behaviour changes.
(Aside:  the worst problems are some changes in either saving or CDL output, not sure which yet but it will be messy to fix)

So, as a quick fix, @ocefpaf offered to provide here an ESMPy build which can work with the earlier netcdf.  That is crucial, otherwise this "shortcut" will not work !

**Comment by pp-mo** [comment]
> It might be simple to sort by specifying all dependencies in one go

In principle, I believe that is what the single-line environment creation does ?
I.E. I am not subsequently installing iris into the env, I run it from my local repo.

**Comment by ajdawson** [comment]
Ah I see that now, I guess I'd expect that to work too...

**Comment by ocefpaf** [comment]
>  It might be simple to sort by specifying all dependencies in one go, at least conda will tell you if there is something that cannot be resolved.

Sadly that is not always true. Conda can still downgrade `libnetcdf` without warning. Ideally we should find which one of those dependencies are forcing the downgrade of `libnetcdf` and re-build it with a modern  libnetcdf (if it is on our side) or we need to rebuild `ESMF`  with `libnetcdf 4.2.1.1`.

**Pull request merged**
