### PR TITLE
Circle-CI py3k

### PR DESCRIPTION
**Pull request by ocefpaf**
Enable Python 3 builds on Circle-CI.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pelson I do not think this is OK. I guess that the pyke's recipe needs the env variable `CONDA_PY=34` for the pre-processor, that selects the source code download, to work properly. It is downloading `pyke-1.1.1.zip` instead of `pyke3-1.1.1.zip`.

**Comment by pelson** [comment]
Merging a commit elsewhere closed this PR. Very strange. I'll merge this once the build matrix has completed for ObviousCI - that PR should have fixed it.

**Comment by ocefpaf** [comment]
OK.  I restored the branch.

**Comment by pelson** [comment]
Looks great. Thanks @ocefpaf.
I'll keep an eye on https://circleci.com/gh/SciTools/conda-recipes-scitools/32

**Comment by pelson** [comment]
> I'll keep an eye on https://circleci.com/gh/SciTools/conda-recipes-scitools/32

Which incidentally is now building py35 variations.

**Comment by pelson** [comment]
After updating the obviousci *and* the Docker container the following build log information was seen:

```
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: pyke3-1.1.1.zip
Downloading http://download.sourceforge.net/pyke/pyke3-1.1.1.zip
```

:+1:

**Comment by pelson** [comment]
That was https://circleci.com/gh/SciTools/conda-recipes-scitools/34

**Comment by ocefpaf** [comment]
Awesome!  I am firing our builds up too.  I am exited for iris in Python3 (3.5!)

**Comment by pelson** [comment]
Incidentally, shapely failed:

```
byte-compiling build/bdist.linux-x86_64/egg/shapely/vectorized/__init__.py to __init__.cpython-35.pyc
creating stub loader for shapely/speedups/_speedups.cpython-35m-x86_64-linux-gnu.so
creating stub loader for shapely/vectorized/_vectorized.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/shapely/speedups/_speedups.py to _speedups.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/shapely/vectorized/_vectorized.py to _vectorized.cpython-35.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying shapely/_geos.pxi -> build/bdist.linux-x86_64/egg/shapely
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Shapely.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Shapely.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Shapely.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Shapely.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
warning: no library file corresponding to '/opt/conda/envs/_build/lib/python3.5/site-packages/numpy/core/include' found (skipping)
zip_safe flag not set; analyzing archive contents...
shapely.speedups.__pycache__._speedups.cpython-35: module references __file__
shapely.vectorized.__pycache__._vectorized.cpython-35: module references __file__
shapely.__pycache__.geos.cpython-35: module references __file__
creating dist
creating 'dist/Shapely-1.5.8-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Shapely-1.5.8-py3.5-linux-x86_64.egg
creating /opt/conda/envs/_build/lib/python3.5/site-packages/Shapely-1.5.8-py3.5-linux-x86_64.egg
Extracting Shapely-1.5.8-py3.5-linux-x86_64.egg to /opt/conda/envs/_build/lib/python3.5/site-packages
Adding Shapely 1.5.8 to easy-install.pth file

Installed /opt/conda/envs/_build/lib/python3.5/site-packages/Shapely-1.5.8-py3.5-linux-x86_64.egg
Processing dependencies for Shapely==1.5.8
Finished processing dependencies for Shapely==1.5.8
found egg dir: /opt/conda/envs/_build/lib/python3.5/site-packages/Shapely-1.5.8-py3.5-linux-x86_64.egg
number of files: 80
Fixing permissions
patchelf: file: /opt/conda/envs/_build/lib/python3.5/site-packages/shapely/speedups/_speedups.cpython-35m-x86_64-linux-gnu.so
    setting rpath to: $ORIGIN/../../../..
patchelf: file: /opt/conda/envs/_build/lib/python3.5/site-packages/shapely/vectorized/_vectorized.cpython-35m-x86_64-linux-gnu.so
    setting rpath to: $ORIGIN/../../../..
Ignored hard-coded path in lib/python3.5/site-packages/shapely/speedups/_speedups.cpython-35m-x86_64-linux-gnu.so
Ignored hard-coded path in lib/python3.5/site-packages/shapely/vectorized/_vectorized.cpython-35m-x86_64-linux-gnu.so
Fixing permissions
BUILD END: shapely-1.5.8-np19py35_2
TEST START: shapely-1.5.8-np19py35_2
Fetching package metadata: ........
Solving package specifications: .
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    shapely-1.5.8              |       np19py35_2         524 KB  file:///opt/conda/conda-bld/linux-64/

The following NEW packages will be INSTALLED:

    geos:        3.4.2-2          scitools                             
    libgfortran: 1.0-0            defaults                             
    numpy:       1.9.2-py35_1     defaults                             
    openblas:    0.2.14-1         defaults                             
    openssl:     1.0.1k-1         defaults                             
    pip:         7.1.2-py35_0     defaults                             
    python:      3.5.0-0          defaults                             
    readline:    6.2-2            defaults                             
    setuptools:  18.1-py35_0      defaults                             
    shapely:     1.5.8-np19py35_2 file:///opt/conda/conda-bld/linux-64/
    sqlite:      3.8.4.1-1        defaults                             
    tk:          8.5.18-0         defaults                             
    wheel:       0.24.0-py35_0    defaults                             
    xz:          5.0.5-0          defaults                             
    zlib:        1.2.8-0          defaults                             

===== testing package: shapely-1.5.8-np19py35_2 =====
import: u'shapely'
import: u'shapely.speedups._speedups'
Traceback (most recent call last):
  File "/opt/conda/conda-bld/test-tmp_dir/run_test.py", line 28, in <module>
    import shapely.speedups._speedups
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/shapely/speedups/__init__.py", line 3, in <module>
    from shapely.geometry import linestring, polygon
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/shapely/geos.py", line 58, in <module>
    _lgeos = load_dll('geos_c', fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
  File "/opt/conda/envs/_test/lib/python3.5/site-packages/shapely/geos.py", line 54, in load_dll
    libname, fallbacks or []))
OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
TESTS FAILED: shapely-1.5.8-np19py35_2
```

**Comment by pelson** [comment]
@ocefpaf - would you mind submitting your Shapely as a PR? I tried, and clearly failed :sob:

**Comment by ocefpaf** [comment]
Doing it now.

**Pull request merged**
