### PR TITLE
Update cf_units to v1.0.0

### PR DESCRIPTION
**Pull request by ocefpaf**
- Refactor of cf_units files.
- Get cf_units ready for drop-in to Iris.

### CODE REVIEW

**Comment by marqh** [comment]
looks grand

thank you @ocefpaf

**Comment by ocefpaf** [comment]
I also made a PyPI release https://pypi.python.org/pypi/cf_units/1.0.0

**Comment by pelson** [comment]
Cool. Thanks @ocefpaf. Would you mind updating the package index owners to include "dkillick, pelson, Ed.Campbell, Bill.Little, rhattersley"?

**Comment by ocefpaf** [comment]
Just did.  Let me know if that worked.

**Comment by pelson** [comment]
It did, but did you remove yourself? If so you needn't - you are as much an owner as anybody else.

**Comment by ocefpaf** [comment]
Too much responsibility :stuck_out_tongue_winking_eye: 

(I was actually just testing how roles work in PyPI.)

**Pull request merged**
