### PR TITLE
Cartopy v0.12

### PR DESCRIPTION
**Pull request by pelson**
Work in progress v0.12.x build of cartopy.

### CODE REVIEW

**Comment by pelson** [comment]
This should be good to go. @dkillick?

**Comment by rhattersley** [comment]
Your AppVeyor build has failed.

**Comment by pelson** [comment]
> Your AppVeyor build has failed.

Argh. Had nothing to do with cartopy, but I'll take a look at fixing that too.

**Comment by ocefpaf** [comment]
It seems that the wget URL is dead.  My knowledge about AppVeyor and installing FOOS on Windows is zero, but it seems that some people install wget with the command `choco install wget`.

**Comment by ocefpaf** [comment]
Never mind, it seems that @pelson already found a PowerShell magic to solve it...

**Comment by pelson** [comment]
> Never mind, it seems that @pelson already found a PowerShell magic to solve it...

Or not... I decided to fall back to trusty Python! :smile: 

This is all dandy now.

**Comment by ocefpaf** [comment]
I was thinking about doing that, but we decided to avoid the download all together and adde the bootstrap script into our repository.

**Comment by pelson** [comment]
> added the bootstrap script into our repository.

I guess that is a common pattern for bootstrap scripts, so can't see any harm with it. Since the bootstrap itself downloads with Python, I'd say both approaches made some sense. :+1:

**Pull request merged**
