### PR TITLE
cf_units v1.1.1

### PR DESCRIPTION
**Pull request by dkillick**
Upped version of cf_units to be built by the recipe to the newly-released v1.1.1.

### CODE REVIEW

**Comment by dkillick** [comment]
I think this is going to require #171 for the build to pass...

**Comment by marqh** [comment]
do #192 and #193 between them mean that this should now work as expected?

**Comment by dkillick** [comment]
@marqh they should; I'm even now rebasing to take advantage of them.

**Comment by dkillick** [comment]
Closing in favour of #171 (which has ended up doing the work in this PR).

**Pull request closed without merging**
