### PR TITLE
Fix #144

### LINKED ISSUE #144: jasper links to /usr/local/lib/libjpeg.8.dylib on osx
The jasper binary for osx64 (1,900,1, build 4) links against a non-standard package outside of conda, namely it expects /usr/local/lib/libjpeg.8.dylib at run-time, but I don't have that installed. This prevents me from using gribapi with iris on osx.

The package build should instead link against the libjpeg provided via conda, which is correctly listed as a build dependency in the jasper recipe. The build process needs to somehow ensure that the correct libjpeg is found by the linker. I don't know the best way of doing this...

### PR DESCRIPTION
**Pull request by ocefpaf**
@ajdawson I don't know the first thing about OS X.  Let's hope this fixes #144.

### CODE REVIEW

**Comment by ajdawson** [comment]
>I don't know the first thing about OS X

Just got a Mac, so I don't know much either!

**Comment by ocefpaf** [comment]
`make check` is passing and we can find the binary via `jasper --version` but that worked before too, so nothing new there.

Can you build this recipe locally and test it against your setup?

**Comment by ajdawson** [comment]
I can't check locally, it will always work because I don't have any other libjasper installed...
The recipe seems to correctly find the conda jasper, but in the case of the existing build it seems to have found a different one.

This kind of problem might be easier to track down if we were able to run `conda inspect linkages ...` on a package once it is built. Could it be part of the test phase perhaps?

**Comment by ocefpaf** [comment]
> I can't check locally, it will always work because I don't have any other libjasper installed...

OK.

> This kind of problem might be easier to track down if we were able to run conda inspect linkages

That would be a nice adding to conda.  Meanwhile I tried this on Linux:

```shell
ldd /home/filipe/miniconda/envs/_test/lib/libjasper.so | grep libjpeg
libjpeg.so.8 => /home/filipe/miniconda/envs/_test/lib/./libjpeg.so.8 (0x00007f89f9ab9000)
```

I guess that, at least on Linux, it seems to be doing the right thing.

**Comment by ajdawson** [comment]
>That would be a nice adding to conda.

It does exist already! I meant can't we just add the line

```
 - conda inspect linkages jasper
```

to the test section of meta.yaml to have it run as part of the build test?

**Comment by ocefpaf** [comment]
> It does exist already! I meant can't we just add the line

By nice addition I meant: run the command as a test that would fail if certain conditions are not met.

**Comment by ajdawson** [comment]
OK, sure it will pass always, but what we need is a way to verify the built package has the correct linkages. Putting this in the test section seems like a reasonable way to do so.

**Comment by ajdawson** [comment]
And by verify I mean a human can check, not automated.

**Comment by ocefpaf** [comment]
> to the test section of meta.yaml to have it run as part of the build test?

If you do that you will get:

```shell
TEST START: jasper-1.900.1-5
Fetching package metadata: ..........
Solving package specifications: .....
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jasper-1.900.1             |                5         286 KB  file:///home/filipe/miniconda/conda-bld/linux-64/

The following NEW packages will be INSTALLED:

    jasper: 1.900.1-5 file:///home/filipe/miniconda/conda-bld/linux-64/
    jpeg:   8d-0      defaults                                         

Fetching packages ...
jasper-1.900.1 100% |###########################################################################################################################| Time: 0:00:00 115.58 MB/s
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################################################################################################| 100%
+ jasper --version
1.900.1
libjasper 1.900.1
+ conda inspect linkages jasper
Package jasper is not installed in /home/filipe/miniconda/envs/_build
TESTS FAILED: jasper-1.900.1-5
```

Some changes are needed in conda-build to used that for checking (human or automated).

**Comment by ocefpaf** [comment]
Let's see if the option `--name _test` will do.  (Got that from another recipe.)

**Comment by ajdawson** [comment]
Should do the trick...

**Comment by ajdawson** [comment]
I'm not sure that build is ever going to start. Good news is specifying the environment name does the trick. We just need to see if the result on osx is satisfactory.

**Comment by ocefpaf** [comment]
I re-started Travis-CI and it seemed to work this time.

**Comment by ajdawson** [comment]
The result looks sensible to me.

**Comment by ocefpaf** [comment]
@ajdawson Can you merge this?  If not I can do that for you.

**Comment by ajdawson** [comment]
I don't have merge rights here, someone else will have to do it.

**Comment by ocefpaf** [comment]
Done.  Let's hope this fix it.

**Comment by ajdawson** [comment]
This works correctly now, thanks @ocefpaf.

**Comment by rhattersley** [comment]
> I don't have merge rights here ...

Fixed. :wink:

**Comment by pelson** [comment]
>>    I don't have merge rights here ...
> Fixed. :wink:

Thanks @rhattersley, and thanks @ocefpaf and @ajdawson for sorting this out. I didn't know about ```conda inspect``` :+1:

**Pull request merged**
