### PR TITLE
Renamed udunits to udunits2

### PR DESCRIPTION
**Pull request by pelson**
As per https://github.com/ioos/conda-reci…pes/pull/554#issuecomment-153054077.

### CODE REVIEW

**Comment by rhattersley** [comment]
Since when was putting the version into the project name a good idea?

**Comment by pelson** [comment]
> Since when was putting the version into the project name a good idea?

udunits and udunits2 are not the same package. They were written by the same group, and do pretty much the same thing, but they expose different lib/ and bin/ content. The recommended approach was put forwards by the udunits folks themselves in https://github.com/ioos/conda-recipes/pull/554#issuecomment-153054077.

**Comment by rhattersley** [comment]
> Since when was putting the version into the project name a good idea?

Sorry, rhetorical question. Just letting off steam.

> The recommended approach was put forwards by the udunits folks themselves in ioos/conda-recipes#554 (comment).

Yes, I'd read that conversation ... with a sinking feeling. I'll shut up now. :wink:

**Comment by ocefpaf** [comment]
> Since when was putting the version into the project name a good idea?

Since never but like the VHS, Blue Ray, etc, sometimes bad ideas became standard practices :wink: 

BTW [fedora](https://admin.fedoraproject.org/pkgdb/package/udunits2/) and many other Linux distros do the same.

**Comment by rhattersley** [comment]
I know I promised to shut up, but I can't help myself ...

```
$ conda list
...
udunits                   2.2.17                        5    scitools
udunits2                  2.2.20                        0    scitools
...
```
_sigh_ :disappointed:

**Pull request merged**
