### PR TITLE
Bump cartopy to 0.13.1

### PR DESCRIPTION
**Pull request by rhattersley**
NB. Will only work once https://github.com/SciTools/cartopy/pull/705 has been merged and the corresponding release has been made.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Iris on Python 3, new release for Cartopy.  Thanks :santa:

**Comment by rhattersley** [comment]
> Thanks :santa:

Nice emoji :grinning:

**Comment by rhattersley** [comment]
Looks like the failures on OSX are https://github.com/Toblerity/Shapely/issues/177 rearing its head again. :unamused:

**Comment by ocefpaf** [comment]
We have patches for shapely 1.5.13 [here](https://github.com/conda-forge/staged-recipes/blob/master/recipes/shapely/).

**Comment by rhattersley** [comment]
Thanks for the link. :+1: What's the best way to proceed? Simply copy the recipe/patches from conda-forge? :expressionless:

**Comment by rhattersley** [comment]
I've gone with copying the conda-forge recipe for now.

**Comment by ocefpaf** [comment]
> Simply copy the recipe/patches from conda-forge?

Right now? It is. Hopefully we will change in the future this by sending changes like this one, a simple shapely patch, to the default channel rather than forking and fragmenting the recipes.

PS: I did not send shapely 1.5.13 to SciTools before because of the unhashable geometry bug.

**Comment by rhattersley** [comment]
Super! Thanks for the help @ocefpaf :+1:

**Comment by ocefpaf** [comment]
Thanks for the new release.  (We need to sort #140 now.)

**Comment by rhattersley** [comment]
NB. The actual build of the merge commit (https://travis-ci.org/SciTools/conda-recipes-scitools/builds/97679828) has failed with an "Unauthorized" 401 error. I've restarted in the hope that it's a glitch!

**Comment by ocefpaf** [comment]
@rhattersley go to http://anaconda.org/scitools and check if the Token is still valid.  You might need to issue a new one.

**Comment by rhattersley** [comment]
I need to dash, sorry ... I'll see if I can get time later.

**Comment by ocefpaf** [comment]
No problem.  Thanks to @pelson's [expand_source.py](https://github.com/ioos/conda-recipes/blob/master/scripts/expand_source.py) we will have the binaries on IOOS as soon as I re-start our CIs :stuck_out_tongue_winking_eye:

**Pull request merged**
