### PR TITLE
Updated Shapely to 1.5.12

### PR DESCRIPTION
**Pull request by ocefpaf**
Removed `stdint.h` and added the `msinttypes` packages instead.

### CODE REVIEW

**Comment by pelson** [comment]
Just checking @ocefpaf - is there a good reason not to merge this?

**Comment by ocefpaf** [comment]
We need to stay away from 1.5.13 until the next cartopy release is out, but 1.5.12 is OK.

**Comment by pelson** [comment]
Having appveyor problems with:

```
Cloning into bare repository '/cygdrive/c/conda/conda-bld/git_cache/__github.com_geopython_OWSLib.git'...
C:/cygwin/usr/libexec/git-core/git-remote-https.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "C:\conda\scripts\obvci_conda_build_dir-script.py", line 9, in <module>
    load_entry_point('Obvious-ci==0.5.0'
```

I thought this was a conda-build issue, but we have the latest released version. Have you seen this one yet?

**Comment by ocefpaf** [comment]
I just removed [cygwin](https://github.com/ioos/conda-recipes/blob/master/appveyor.yml#L36).  (I guess that my only tool is a hammer.)

**Pull request merged**
